import type React from "react"
import type { Metadata } from "next"
import "../styles/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'sonner';
import { NextIntlClientProvider } from "next-intl"

export const metadata: Metadata = {
  title: "Multi AI Chatroom",
  description: "Generated by Eric",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
                <Toaster position="top-center" />
                {children}
            </ThemeProvider>
      </body>
    </html>
  )
}
